# Either Access Keys or Profile name are required
AWS_ACCESS_KEY_ID: ''
AWS_SECRET_ACCESS_KEY: ''
AWS_CREDENTIALS_PROFILE_NAME: ''

ECS_SERVICE:
  DOCKER_IMAGE: 'milesg/tda-cleaner:latest'
  MEMORY_LIMIT_GB: 16
  COMMAND: 'dask-worker {internal_ip_address}:{port_number} --nanny --nprocs 2'
  INSTANCE_TYPE: 'm4.xlarge'

EMR_SERVICE:
  PYTHON_PACKAGES:
    - matplotlib
    - pandas
    - numpy
    - requests
  INSTANCE_TYPE: 'm4.xlarge'

BATCH_SERVICE:
  DOCKER_IMAGE: 'milesg/tda-cleaner:latest'
  INSTANCE_TYPE: 'm4.xlarge'

EMR_SERVICE:
  SQL_FILE: emr_service/sql_start.sql
