
version: "3"

services:

  influxdb:
    image: influxdb:1.7-alpine
    hostname: influxdb
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      INFLUXDB_DB: admin
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - 3000:3000
